# Generated by Django 4.1.4 on 2022-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeyal', '0002_day_sticker_tag_event_day_stickers_day_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default="2222-12-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='date',
            field=models.DateField(default="2222-12-12"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
