# Generated by Django 4.1.4 on 2022-12-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeyal', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='cal_image',
            field=models.ImageField(blank=True, null=True, upload_to='cal_covers'),
        ),
    ]
