# Generated by Django 4.1.4 on 2022-12-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeyal', '0006_calendar_cal_image'),
        ('journeyal', '0006_journal_tags'),
    ]

    operations = [
    ]
