# Generated by Django 4.1.4 on 2022-12-22 15:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('journeyal', '0007_merge_0006_calendar_cal_image_0006_journal_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
