# Generated by Django 4.1.4 on 2022-12-28 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeyal', '0009_journalimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='user',
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendars_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='users',
            field=models.ManyToManyField(related_name='calendars_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
