# Generated by Django 4.1.4 on 2022-12-29 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeyal', '0011_alter_calendar_owner_alter_calendar_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='journal_files')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_files', to='journeyal.journal')),
            ],
        ),
    ]
