# Generated by Django 4.1.4 on 2023-01-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeyal', '0013_alter_calendar_options_calendar_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
